# Домашнее задание к занятию «Python для анализа данных: numpy и scipy»

**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [131]:
N=10
np.linspace(N-1, 0, N)

array([9., 8., 7., 6., 5., 4., 3., 2., 1., 0.])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [132]:
N=10
a = np.zeros((N, N))
i,j = np.indices(a.shape)
a[i==j] = N
print(a)

[[10.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 10.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 10.]]


In [133]:
N=10
np.diag(np.linspace(N-1, 0, N))

array([[9., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 6., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**Задание 3**
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [134]:
import pandas as pd
ratings = pd.read_csv('ratings.csv')
import pandas as pd
#ratings.head(5)
ratings_filtr=ratings[ratings['rating']==5.0]
#ratings_filtr.head(5)
film_leader=ratings_filtr['movieId'].value_counts()
film_leader.head(1)

318    153
Name: movieId, dtype: int64

**Задание 4**
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [135]:
import pandas as pd
power = pd.read_csv('power.csv')
#power.head(5)
fc = power[ (power['country']=='Latvia') | (power['country']=='Lithuania') | (power['country']=='Estonia')]
#fc.head(10)
fc1= fc[(fc['category']==4)| (fc['category']==12)| (fc['category']==21)]
#fc1.head(10)
fc2= fc1[(fc1['year']>=2005)& (fc1['year']<=2010)]
#fc2.head(5)
fc3=fc2[fc2['quantity']>=0]
fc3.head(5)
sum_power=fc3['quantity'].sum()
print(sum_power)

240580.0


**Задание 5**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [136]:
import numpy as np
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [5, 4, 0]] )
b = np.array( [4, 12, -3])
linalg.solve(a, b)

array([-5.18181818,  5.72727273, 13.27272727])

In [137]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True